# Generated by Django 2.1.5 on 2019-02-11 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articale',
            new_name='Article',
        ),
    ]
